#!/bin/bash
# =============================================================================
# Amplicon Pipeline Setup Script
# Run once after cloning to configure the pipeline for your account
# =============================================================================

set -euo pipefail

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

echo ""
echo "============================================================"
echo "  Amplicon Pipeline Setup"
echo "============================================================"
echo "  Repo directory: $REPO_DIR"
echo ""

# ------------------------------------------------------------------------------
# 1. Generate config.sh
# ------------------------------------------------------------------------------

echo "--- Generating config.sh ---"

read -p "  Enter your email address for SLURM notifications: " USER_EMAIL

cat > "$REPO_DIR/config.sh" << EOF
#!/bin/bash
# Auto-generated by setup.sh — do not commit this file
# Re-run setup.sh to regenerate, or edit manually

PIPELINE_DIR="$REPO_DIR"
SLURM_EMAIL="$USER_EMAIL"
EOF

echo "  config.sh written."

# ------------------------------------------------------------------------------
# 2. Install run_asv2otu command
# ------------------------------------------------------------------------------

echo ""
echo "--- Installing run_asv2otu command ---"

chmod +x "$REPO_DIR/run_asv2otu.sh"
mkdir -p "$HOME/bin"
ln -sf "$REPO_DIR/run_asv2otu.sh" "$HOME/bin/run_asv2otu"
echo "  Symlink created: ~/bin/run_asv2otu -> $REPO_DIR/run_asv2otu.sh"

# Disable file mode tracking so chmod +x never blocks git pull
git -C "$REPO_DIR" config core.fileMode false
echo "  Git file mode tracking disabled (prevents chmod blocking git pull)"

# Ensure ~/bin is on PATH in ~/.bash_profile (sourced by SSH login shells on MSI)
# ~/.bashrc is not reliably sourced at login and conda init can override PATH additions there
if ! grep -q 'export PATH="$HOME/bin:$PATH"' "$HOME/.bash_profile" 2>/dev/null; then
    echo '' >> "$HOME/.bash_profile"
    echo '# Added by HTS_ASV2OTU setup' >> "$HOME/.bash_profile"
    echo 'export PATH="$HOME/bin:$PATH"' >> "$HOME/.bash_profile"
    echo "  Added ~/bin to PATH in ~/.bash_profile"
    echo "  NOTE: Run 'source ~/.bash_profile' for run_asv2otu to be available in this session."
else
    echo "  ~/bin already on PATH in ~/.bash_profile"
fi

# ------------------------------------------------------------------------------
# 3. Create conda environment
# ------------------------------------------------------------------------------

echo ""
echo "--- Setting up conda environment ---"

# load conda module
module load conda

# Source conda
CONDA_BASE=$(conda info --base 2>/dev/null) || { echo "ERROR: conda not found. Please load/install conda first."; exit 1; }
source "$CONDA_BASE/etc/profile.d/conda.sh"

if conda env list | grep -q "itsx_env"; then
    echo "  itsx_env already exists, skipping creation."
else
    echo "  Creating itsx_env (this may take several minutes)..."
    conda create -n itsx_env -c bioconda -c conda-forge \
        itsx vsearch blast bioconductor-dada2 \
        r-dplyr r-tidyr r-readr r-tibble r-purrr r-stringr -y
    echo "  itsx_env created successfully."
fi

# Activate and configure
conda activate itsx_env
export PATH="$HOME/.conda/envs/itsx_env/bin:$PATH"
unset R_HOME 2>/dev/null || true

# ------------------------------------------------------------------------------
# 4. Validate R packages
# ------------------------------------------------------------------------------

echo ""
echo "--- Validating R packages ---"

CONDA_R="$HOME/.conda/envs/itsx_env/bin/Rscript"

if [ ! -f "$CONDA_R" ]; then
    echo "ERROR: conda Rscript not found at $CONDA_R"
    exit 1
fi

PACKAGES="dada2 dplyr tidyr readr tibble purrr stringr"
ALL_OK=true

for pkg in $PACKAGES; do
    if $CONDA_R -e "library($pkg)" 2>/dev/null; then
        echo "  $pkg: OK"
    else
        echo "  $pkg: MISSING"
        ALL_OK=false
    fi
done

if [ "$ALL_OK" = false ]; then
    echo ""
    echo "WARNING: Some packages are missing. Try running:"
    echo "  conda install -n itsx_env -c conda-forge -c bioconda <package_name>"
    exit 1
fi

# ------------------------------------------------------------------------------
# 5. Compile mumu
# ------------------------------------------------------------------------------

echo ""
echo "--- Setting up mumu ---"

MUMU_BIN="$HOME/packages/mumu/mumu"

if [ -f "$MUMU_BIN" ]; then
    echo "  mumu binary already exists, skipping compilation."
else
    echo "  Compiling mumu..."
    # Check if gcc/13.1.0 is available via module
    if module load gcc/13.1.0-5z64cho 2>/dev/null; then
        echo "  Loaded gcc/13.1.0"
    else
        echo "  WARNING: Could not load gcc/13.1.0-5z64cho — will try system gcc"
    fi

    mkdir -p "$HOME/packages"
    if [ ! -d "$HOME/packages/mumu" ]; then
        git clone https://github.com/frederic-mahe/mumu.git "$HOME/packages/mumu"
    fi
    (cd "$HOME/packages/mumu" && make && make check)
    chmod +x "$MUMU_BIN"
    echo "  mumu compiled successfully."
fi

# Validate mumu
if "$MUMU_BIN" --version 2>/dev/null || "$MUMU_BIN" --help 2>/dev/null | head -1; then
    echo "  mumu: OK"
else
    echo "  WARNING: mumu binary exists but may not be functional. Test manually:"
    echo "  $MUMU_BIN --help"
fi

# ------------------------------------------------------------------------------
# 6. Check databases
# ------------------------------------------------------------------------------

echo ""
echo "--- Checking databases ---"

SHARED_DB="/projects/standard/kennedyp/shared/taxonomy"

declare -A DB_FILES
DB_FILES["UNITE (ITS1/ITS2 default)"]="sh_general_release_dynamic_all_19.02.2025_wKennedySynmock.fasta"
DB_FILES["SILVA (16S-V4 default)"]="silva_nr99_v138.1_train_set.fa"
DB_FILES["PR2 (18S-V4 default)"]="pr2_version_5.1.1_SSU_dada2.fasta"
DB_FILES["Maarjam (18S-AMF default)"]="maarjam_dada2.txt"
DB_FILES["EukaryomeITS (--db EukaryomeITS)"]="DADA2_EUK_ITS_v2.0_wKennedySynmock.fasta"
DB_FILES["EukaryomeSSU (--db EukaryomeSSU)"]="DADA2_EUK_SSU_v2.0.fasta"

ALL_DB_OK=true
for db_label in "${!DB_FILES[@]}"; do
    db="${DB_FILES[$db_label]}"
    if [ -f "$SHARED_DB/$db" ]; then
        echo "  $db_label: OK"
    else
        echo "  $db_label: NOT FOUND at $SHARED_DB/$db"
        ALL_DB_OK=false
    fi
done

if [ "$ALL_DB_OK" = false ]; then
    echo ""
    echo "WARNING: Some databases not found. Contact your PI or check shared directory:"
    echo "  $SHARED_DB"
fi

# ------------------------------------------------------------------------------
# Done
# ------------------------------------------------------------------------------

echo ""
echo "============================================================"
echo "  Setup complete!"
echo ""
echo "  Run the pipeline with:"
echo "  run_asv2otu <project_dir> <asv_table_path> <proj_name> <primer_set> [--skip-itsx] [--db <database>]"
echo ""
echo "  Primer Set Options:"
echo "  ITS1    - fungal ITS1 region (UNITE database, ITSx optional)"
echo "  ITS2    - fungal ITS2 region (UNITE database, ITSx optional)"
echo "  16S-V4  - bacterial 16S V4 region (SILVA database, no ITSx)"
echo "  18S-V4  - microeukaryote 18S V4 region (PR2 database, no ITSx)"
echo "  18S-AMF - arbuscular mycorrhizal fungi 18S (MaarjAM database, no ITSx)"
echo ""
echo "  DATABASE OPTIONS (if manually chosen, using flag --db):"
echo "  SILVA        - bacteria SSU 16S rRNA sequences"
echo "  UNITE        - fungal ITS1 and ITS2 regions"
echo "  PR2          - full-length SSU 18S sequences, covers whole eukaryote tree but with focus on protists"
echo "  Maarjam      - AMF 18S SSU sequences"
echo "  EukaryomeITS - ITS1 and ITS2 sequences with good coverage across the eukaryote tree"
echo "  EukaryomeSSU - 18S SSU sequences with good coverage across the eukaryote tree (especially for AMF?)"
echo ""
echo "  Example:"
echo "  run_asv2otu /path/to/project /path/to/ASVtable.tsv FAB2 ITS2"
echo ""
echo "  NOTE: run_asv2otu can be run from any directory on the cluster."
echo " "
echo "============================================================"
echo ""